### ISSUE TITLE
Link nel report

### ISSUE THREAD

**Issue by EliaCereda** [GiorgiaAuroraAdorni/MosquitoDiseaseSpreadRatePrediction#4]
In questo momento ci sono una serie di `\href` nel report che sono cliccabili ma hanno lo stesso colore del testo e non mostrano l'URL di destinazione. In qualche modo dobbiamo sistemarli.

* Possiamo cambiare il colore dei link per rendere esplicito cosa si possa cliccare
* Possiamo mostrare l'intero URL nel testo
* Possiamo fare una bibliografia vera e propria

**Comment by GiorgiaAuroraAdorni** [comment]
Allora la bibliografia al momento c'è già, potremmo mettere un piè di pagina per i link scritti per esteso

**Comment by EliaCereda** [comment]
Ah non avevo visto. In questo momento la bibliografia compare nell'indice ma nel documento poi non c'è. È solo perché è vuota?

**Comment by EliaCereda** [comment]
Piè di pagina a me piace, se @ericniso è d'accordo possiamo fare così.

**Comment by GiorgiaAuroraAdorni** [comment]
Esattamente, però forse, siccome avremo poco reference, conviene metterle a pie di pagina. A breve pubblico una soluzione.
